version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.17
    - 6.1.20
    - 6.1.21
    - 6.2.3
    - 6.2.7
    - 6.2.9
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.18
  - dependency-name: "@ampproject/filesize"
    versions:
    - 4.3.0
